device: 0
save_dir : 'log'

data:
  train_file: 'data/ptb-train.pickle'
  val_file: 'data/ptb-val.pickle'
  test_file: 'data/ptb-test.pickle'
  vocab_type: 'max_size'
  vocab_size: 10000
  min_freq: 2




model:
  model_name: 'simple_NPCFG_split'
  NT: 1024
  T: 8192
  s_dim: 512
  w_dim: 512
  h_dim: 512
  z_dim: 64


train:
  batch_size: 16
  max_epoch: 20
  max_len: 40
  #whether to use curriculum learning stragegy.
  curriculum: 1
  start_len: 30
  increment: 0
  patience: 5
  clip: 3

test:
  batch_size: 16
  max_tokens: 100
  bucket: 32
  decode: 'mbr'
  sampler: 'batch'

optimizer:
  name: 'adam'
  lr: 0.002
  mu: 0.99
  nu: 0.999





